CREATE TABLE IF NOT EXISTS nodes (
    uuid TEXT PRIMARY KEY,
    subtree_uuid TEXT,
    parent_uuid TEXT,
    channel INTEGER,
    char_position_in_line INTEGER,
    char_start_index INTEGER,
    char_stop_index INTEGER,
    start_line_index INTEGER,
    stop_line_index INTEGER,
    line_count INTEGER,
    node_type TEXT,
    rule TEXT,
    start_token_number INTEGER,
    stop_token_number INTEGER,
    subtree_depth INTEGER,
    subtree_node_text TEXT,
    subtree_size INTEGER,
    subtree_string TEXT,
    text TEXT,
    text_sha256 TEXT,
    token TEXT,
    token_index INTEGER,
    token_name TEXT,
    token_type INTEGER,
    fortran_file TEXT
);
